; s3-defender — LilyGO T-Dongle-S3
; https://github.com/Xinyuan-LilyGO/T-Dongle-S3

[env:t-dongle-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D CORE_DEBUG_LEVEL=0
  -D S3_DEFENDER_SOFTAP_SSID=\"S3-Defender\"
lib_deps =
  bblanchon/ArduinoJson @ ^7.2.1
