#pragma once
// GENERATED from data/index.html by tools/gen_web_assets.py -- do not edit.

static const char INDEX_HTML[] PROGMEM =
  "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\" />\n<meta name=\"viewport\""
  " content=\"width=device-width, initial-scale=1, viewport-fit=cover\" />\n"
  "<title>s3-defender</title>\n<meta name=\"theme-color\" content=\"#0b1020\" />\n<link rel=\""
  "manifest\" href=\"/manifest.webmanifest\" />\n<link rel=\"icon\" href=\"/favicon-32.png\" />\n"
  "<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/apple-touch-icon.png\" />\n"
  "<meta name=\"apple-mobile-web-app-capable\" content=\"yes\" />\n<meta name=\""
  "apple-mobile-web-app-status-bar-style\" content=\"black-translucent\" />\n<meta name=\""
  "apple-mobile-web-app-title\" content=\"s3-defender\" />\n<style>\n  :root {\n"
  "    color-scheme: dark;\n"
  "    --bg: #0b1020; --panel: #131a2e; --panel2: #1a2340; --line: #26304d;\n"
  "    --text: #e8ecf4; --dim: #97a1b8; --accent: #7fd4ff; --good: #46d68c;\n"
  "    --warn: #ffb454; --bad: #ff5f6d;\n  }\n  * { box-sizing: border-box; }\n"
  "  body { margin: 0; background: var(--bg); color: var(--text);\n"
  "         font: 14px/1.45 system-ui, sans-serif; padding-bottom: 2rem; }\n"
  "  header { padding: 0.8rem 1rem 0.5rem; position: sticky; top: 0; z-index: 5;\n"
  "           background: linear-gradient(var(--bg) 82%, rgba(11,16,32,0)); }\n"
  "  h1 { font-size: 1.05rem; margin: 0; display: flex; align-items: center; gap: 0.5rem;\n"
  "       letter-spacing: 0.02em; }\n"
  "  .dot { width: 9px; height: 9px; border-radius: 50%; background: var(--bad);\n"
  "         box-shadow: 0 0 6px currentColor; display: inline-block; }\n"
  "  .dot.live { background: var(--good); }\n  .dot.poll { background: var(--warn); }\n"
  "  #meta { display: flex; flex-wrap: wrap; gap: 0.35rem 0.9rem; color: var(--dim);\n"
  "          font-size: 0.78rem; margin: 0.4rem 0 0.55rem; }\n  #heap { min-width: 7rem; }\n"
  "  .chip { padding: 0.28rem 0.85rem; border-radius: 999px; border: 1px solid var(--line);\n"
  "          background: var(--panel); color: var(--dim); font: inherit; font-size: 0.8rem;\n"
  "          cursor: pointer; }\n"
  "  .chip.on { background: var(--panel2); color: var(--accent); border-color: #37507e; }\n"
  "  section { border: 1px solid var(--line); border-radius: 10px; margin: 0.6rem 1rem;\n"
  "            overflow: hidden; background: var(--panel); }\n"
  "  section h2 { font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.12em;\n"
  "               color: var(--accent); margin: 0; padding: 0.55rem 0.8rem;\n"
  "               display: flex; justify-content: space-between; align-items: center; }\n"
  "  section h2 .cnt { color: var(--dim); text-transform: none; letter-spacing: 0; }\n"
  "  .row { display: flex; justify-content: flex-end; gap: 0.5rem; align-items: center;\n"
  "         color: var(--dim); font-size: 0.72rem; padding: 0 0.8rem 0.55rem; }\n"
  "  select, .more > a { background: var(--panel2); color: var(--text); border: 1px solid var(--line);\n"
  "                      border-radius: 6px; font: inherit; font-size: 0.72rem; padding: 0.15rem; }\n"
  "  ul { list-style: none; margin: 0; padding: 0; }\n"
  "  li { display: grid; grid-template-columns: 3.4rem 1fr auto; gap: 0.55rem;\n"
  "       align-items: center; padding: 0.44rem 0.8rem; border-top: 1px solid #1c2540; }\n"
  "  li.new { background: rgba(127, 212, 255, 0.07); }\n"
  "  li .rssi { height: 5px; border-radius: 3px; background: #202842; position: relative;\n"
  "             overflow: hidden; }\n  li .rssi i { position: absolute; inset: 0; width: 0;\n"
  "               border-radius: 3px; background: var(--accent); }\n  li .id { min-width: 0; }\n"
  "  li .id .name { display: block; overflow: hidden; text-overflow: ellipsis;\n"
  "                 white-space: nowrap; }\n"
  "  li .id .sub { color: var(--dim); font-size: 0.68rem; font-family: var(--mono, monospace); }\n"
  "  li .tag { color: var(--dim); font-size: 0.68rem; text-align: right; white-space: nowrap; }\n"
  "  li .tag b { color: var(--text); }\n"
  "  .more { padding: 0.5rem 0.8rem; font-size: 0.75rem; border-top: 1px solid #1c2540; }\n"
  "  .more a { cursor: pointer; }\n"
  "  footer { margin: 1rem; color: var(--dim); font-size: 0.75rem; line-height: 1.8; }\n"
  "  footer a { color: var(--accent); text-decoration: none; }\n"
  "  #toast { position: fixed; left: 50%; bottom: 1.4rem; transform: translateX(-50%);\n"
  "           background: var(--panel2); color: var(--warn); border: 1px solid var(--line);\n"
  "           border-radius: 8px; padding: 0.4rem 0.9rem; font-size: 0.78rem; opacity: 0;\n"
  "           transition: opacity 0.25s; pointer-events: none; }\n"
  "  .empty { color: var(--dim); font-size: 0.78rem; padding: 0.6rem 0.8rem; }\n</style>\n</head>\n"
  "<body>\n<header>\n  <h1>s3-defender <span id=\"live\" class=\"dot\" title=\"connecting\""
  "></span></h1>\n  <div id=\"meta\">\n    <span id=\"m-uptime\">\342\200\223</span>\n"
  "    <span id=\"m-heap\" title=\"free / minimum free / fragmentation\">\342\200\223</span>\n"
  "    <span id=\"m-scan\" title=\"radio state\">\342\200\223</span>\n    <span id=\"m-sd\">\342"
  "\200\223</span>\n  </div>\n  <div>\n    <button class=\"chip\" data-mode=\"wifi\""
  ">Wi-Fi</button>\n    <button class=\"chip\" data-mode=\"ble\">BLE</button>\n    <button class=\""
  "chip\" data-mode=\"both\">Both</button>\n  </div>\n</header>\n\n<main>\n  <section>\n"
  "    <h2>Wi-Fi <span class=\"cnt\" id=\"cnt-w\">\342\200\223</span></h2>\n    <div class=\"row\""
  ">\n      <label><input type=\"checkbox\" id=\"hide-w\" /> hidden SSIDs</label>\n"
  "      <select id=\"sort-w\">\n        <option value=\"rssi\">RSSI</option>\n"
  "        <option value=\"ch\">Channel</option>\n        <option value=\"name\">Name</option>\n"
  "        <option value=\"age\">Age</option>\n      </select>\n    </div>\n    <ul id=\"list-w\""
  "></ul>\n    <div class=\"more\" id=\"more-w\" hidden></div>\n  </section>\n\n  <section>\n"
  "    <h2>BLE <span class=\"cnt\" id=\"cnt-b\">\342\200\223</span></h2>\n    <div class=\"row\">\n"
  "      <select id=\"sort-b\">\n        <option value=\"rssi\">RSSI</option>\n"
  "        <option value=\"name\">Name</option>\n        <option value=\"age\">Age</option>\n"
  "      </select>\n    </div>\n    <ul id=\"list-b\"></ul>\n    <div class=\"more\" id=\"more-b\""
  " hidden></div>\n  </section>\n</main>\n\n<footer>\n  <div><a id=\"dl\" hidden href=\""
  "/download?file=log.csv\">&#x2B07; download log.csv</a>\n       <span id=\"sd-note\""
  "></span></div>\n  <div id=\"ver\"></div>\n"
  "  <div>Add to Home Screen for app-like install &middot; <a href=\"/manifest.webmanifest\""
  ">manifest</a></div>\n</footer>\n\n<div id=\"toast\"></div>\n\n<script>\n\"use strict\";\n"
  "// ---- file:// dev shim (device serves the real thing) -----------------------\n"
  "if (location.protocol === \"file:\") {\n  var mk = function (n, base) {\n    var a = [];\n"
  "    for (var i = 0; i < n; i++) a.push({\n      ssid: base == \"w\" ? [\"Home\", \"Neighbour\""
  ", \"Hidden-\" + i, \"Cafe \" + i][i % 4] : (i % 3 ? \"\" : \"Test-\" + i),\n      bssid: \""
  "f0:9f:c2:\" + (10 + i) % 100 + \":1d:3a\", rssi: -40 - (i * 4) % 48, ch: 1 + (i * 3) % 13,\n"
  "      auth: [\"wpa2\", \"wpa3\", \"open\""
  "][i % 3], seen_ms: (i * 1300) % 11000, first_ms: (i * 900) % 60000, n: i * 11 + 3 });\n"
  "    return a;\n  };\n"
  "  var bk = function (n) { var a = []; for (var i = 0; i < n; i++) a.push({\n    name: i % 2 ? \""
  "\" : [\"TV Remote\", \"Watch\", \"Sensor-\" + i][i % 3],\n    addr: \"3c:71:bf:\""
  " + (9 + i) % 100 + \":e2:0d\", at: [2, 1, 0][i % 3], rssi: -45 - (i * 5) % 50,\n"
  "    seen_ms: (i * 1700) % 9000, first_ms: (i * 700) % 50000, n: i * 7 + 2,\n"
  "    conn: !(i % 3), adv_len: 6 + (i * 9) % 26 });\n    return a; };\n"
  "  window.__snap = function () { var k = (Date.now() / 1000) | 0; return {\n    name: \""
  "s3-defender\", ver: \"dev-shim\", mode: \"both\", uptime_s: k % 3600, epoch_s: 0,\n"
  "    heap: { free: 128000 - (k % 90), min: 121000, frag_pct: 4 },\n    scan: { wifi: \"scanning\""
  ", ble: \"scanning\", next_s: (3 - (k % 3)) },\n    wifi_count: 37, ble_count: 12,\n"
  "    wifi: mk(24, \"w\"), ble: bk(12),\n    sd: { mounted: true, files: [\"log.csv\""
  "], used_bytes: 48211, card_bytes: 32768673792 },\n    ws: { clients: 1, topk: 24 } }; };\n"
  "  window.fetch = function (u, o) {\n    var s = String(u); var body = \"\";\n"
  "    if (s.indexOf(\"/api/mode\") >= 0)\n      body = JSON.stringify({ ok: true, mode: s.split(\""
  "mode=\")[1] || \"both\" });\n    else if (s.indexOf(\"/api/list\") >= 0)\n"
  "      body = JSON.stringify(window.__snap());\n    else\n"
  "      body = JSON.stringify(window.__snap());\n    return Promise.resolve(new Response(body,\n"
  "      { status: 200, headers: { \"content-type\": \"application/json\" } }));\n  };\n"
  "  function WS(u) { var t = Math.max(50, 1000 - (Date.now() % 900)),\n"
  "    self = this; self.send = self.close = function () {};\n"
  "    self.onmessage = self.onopen = self.onclose = function () {};\n"
  "    setTimeout(function () { if (self.onopen) self.onopen({ type: \"open\" });\n"
  "      self.onmessage({ data: JSON.stringify(window.__snap()) }); }, t);\n"
  "    this.readyState = 1; }\n  window.WebSocket = WS;\n}\n"
  "// ---- end shim ----------------------------------------------------------------\n\n"
  "var $ = function (id) { return document.getElementById(id); };\n"
  "var state = { ws: null, pollTimer: null, pollFails: 0, lastMode: null, full: null };\n"
  "var sortW = localStorage.getItem(\"sort-w\") || \"rssi\";\nvar sortB = localStorage.getItem(\""
  "sort-b\") || \"rssi\";\n$(\"sort-w\").value = sortW; $(\"sort-b\").value = sortB;\n\n"
  "function toast(msg) {\n  var t = $(\"toast\"); t.textContent = msg; t.style.opacity = 1;\n"
  "  clearTimeout(t._h); t._h = setTimeout(function () { t.style.opacity = 0; }, 2200);\n}\n"
  "function age(ms) { var s = Math.round(ms / 1000); return s < 90 ? s + \"s\" : (s / 60 | 0) + \""
  "m\"; }\nfunction rssiPct(r) { return Math.max(2, Math.min(100, (r + 95) / 55 * 100)); }\n"
  "function esc(s) { var d = document.createElement(\"div\""
  "); d.textContent = s; return d.innerHTML; }\n"
  "function fmt(k) { return k > 1048576 ? (k / 1048576).toFixed(1) + \" MB\" : (k / 1024 | 0) + \""
  " KB\"; }\n\nfunction render(d) {\n  $(\"m-uptime\").textContent = \"up \""
  " + (d.uptime_s / 3600 | 0) + \"h \" +\n"
  "                              (d.uptime_s / 60 % 60 | 0) + \"m\";\n  $(\"m-heap\""
  ").textContent = \"heap \" + Math.round(d.heap.free / 1024) + \"k / \" +\n"
  "                            Math.round(d.heap.min / 1024) + \"k\" + \" \302\267 frag \""
  " + d.heap.frag_pct + \"%\";\n  $(\"m-scan\").textContent = \"scan \" + d.scan.wifi + \"/\""
  " + d.scan.ble +\n                            (d.scan.next_s ? \" \302\267 next \""
  " + d.scan.next_s + \"s\" : \"\");\n  $(\"m-sd\").textContent = d.sd.mounted\n    ? \"sd \""
  " + (d.sd.used_bytes / 1024 | 0) + \"k/\" + Math.round(d.sd.card_bytes / 1.074e9 * 10) / 10 + \""
  "G\"\n    : \"no sd\";\n  var live = $(\"live\");\n  for (var i = 0; i < 3; i++) {\n"
  "    var b = document.querySelectorAll(\".chip\")[i];\n    b.classList.toggle(\"on\""
  ", b.dataset.mode === d.mode);\n    b.disabled = b.dataset.mode === d.mode;\n  }\n"
  "  state.lastMode = d.mode;\n  $(\"cnt-w\""
  ").textContent = d.wifi_count + (d.wifi.length < d.wifi_count ? \" of \" + d.wifi.length : \"\""
  ");\n  $(\"cnt-b\").textContent = d.ble_count + (d.ble.length < d.ble_count ? \" of \""
  " + d.ble.length : \"\");\n  renderWifi(d); renderBle(d);\n  $(\"dl\").hidden = !d.sd.mounted;\n"
  "  $(\"sd-note\").textContent = d.sd.mounted ? fmt(d.sd.used_bytes) + \" logged\" : \"\";\n  $(\""
  "ver\").textContent = d.name + \" \302\267 \" + d.ver + \" \302\267 ws \" + d.ws.clients;\n"
  "  var mw = d.wifi_count > d.wifi.length ? $(\"more-w\") : ($(\"more-w\").hidden = true);\n"
  "  if (mw) { mw.hidden = false; mw.innerHTML = '<a onclick=showAll(\"w\")>show all (first ' +\n"
  "    d.wifi_count + \" by rssi)</a>\"; }\n  var mb = d.ble_count > d.ble.length ? $(\"more-b\""
  ") : ($(\"more-b\").hidden = true);\n"
  "  if (mb) { mb.hidden = false; mb.innerHTML = '<a onclick=showAll(\"b\")>show all</a>'; }\n}\n\n"
  "function renderWifi(d) {\n  var now = d.uptime_s, list = d.wifi.slice(0);\n  var k = $(\""
  "sort-w\").value;\n  if (k === \"name\") list.sort(function (a, b) { return (a.ssid || \"\""
  ").localeCompare(b.ssid || \"\"); });\n  else if (k === \"ch\""
  ") list.sort(function (a, b) { return a.ch - b.ch || a.rssi - b.rssi; });\n  else if (k === \""
  "age\") list.sort(function (a, b) { return a.seen_ms - b.seen_ms; });\n"
  "  else list.sort(function (a, b) { return b.rssi - a.rssi; });\n  var hide = $(\"hide-w\""
  ").checked;\n  var out = \"\";\n  for (var i = 0; i < list.length; i++) {\n"
  "    var w = list[i]; if (hide && !w.ssid) continue;\n"
  "    out += '<li' + (w.first_ms < 5000 ? ' class=\"new\"' : \"\") + \">\"\n"
  "      + '<div><span class=\"rssi\"><i style=\"width:' + rssiPct(w.rssi) + '%\"></i></span>'\n"
  "      + w.rssi + \"dBm</div>\"\n      + \"<div class=\\\"id\\\"><span class=\\\"name\\\">\""
  " + esc(w.ssid || \"(hidden)\") + \"</span>\"\n      + \"<span class=\\\"sub\\\">ch\" + w.ch + \""
  " \302\267 \" + w.auth + \" \302\267 \" + w.bssid + \"</span></div>\"\n      + '<div class=\""
  "tag\">age <b>' + age(w.seen_ms) + \"</b></div></li>\";\n  }\n  $(\"list-w\""
  ").innerHTML = out || '<li class=\"empty\">listening\342\200\246</li>';\n}\n\n"
  "function renderBle(d) {\n  var list = d.ble.slice(0), k = $(\"sort-b\").value;\n  if (k === \""
  "name\") list.sort(function (a, b) { return (a.name || \"~\").localeCompare(b.name || \"~\""
  "); });\n  else if (k === \"age\""
  ") list.sort(function (a, b) { return a.seen_ms - b.seen_ms; });\n"
  "  else list.sort(function (a, b) { return b.rssi - a.rssi; });\n  var AT = [\"pub\", \"rnd\", \""
  "rpa\", \"nrpa\"], out = \"\";\n  for (var i = 0; i < list.length; i++) {\n    var b = list[i];\n"
  "    out += '<li' + (b.first_ms < 5000 ? ' class=\"new\"' : \"\") + \">\"\n"
  "      + '<div><span class=\"rssi\"><i style=\"width:' + rssiPct(b.rssi) + '%\"></i></span>'\n"
  "      + b.rssi + \"dBm</div>\"\n      + \"<div class=\\\"id\\\"><span class=\\\"name\\\">\""
  " + esc(b.name || \"unnamed\") + \"</span>\"\n      + \"<span class=\\\"sub\\\">\" + b.addr + \""
  " \302\267 \" + AT[b.at] + (b.conn ? \" \302\267 c\" : \"\") + \"</span></div>\"\n"
  "      + '<div class=\"tag\">age <b>' + age(b.seen_ms) + \"</b> \302\267 \" + b.adv_len + \""
  "B</div></li>\";\n  }\n  $(\"list-b\").innerHTML = out || '<li class=\"empty\">listening\342\200"
  "\246</li>';\n}\n\nfunction showAll(kind) {\n  fetch(\"/api/list?kind=\" + kind + \"&limit=128\""
  ").then(function (r) { return r.json(); })\n    .then(function (j) {\n"
  "      var patch = kind === \"w\" ? { wifi: j.wifi, wifi_count: j.wifi.length }\n"
  "                               : { ble: j.ble, ble_count: j.ble.length };\n"
  "      render(Object.assign({}, lastSnap || {}, patch));\n      toast((kind === \"w\" ? \""
  "wifi: \" : \"ble: \") + patch.wifi_count + \" listed\");\n    }).catch(function () { toast(\""
  "show-all failed\"); });\n}\n\n"
  "// ---- transport: WS with backoff, then polling --------------------------------\n"
  "function connect() {\n  try { var u = \"ws://\" + location.host + \"/ws\""
  "; if (location.protocol === \"https:\") u = \"wss://\" + location.host + \"/ws\";\n"
  "    state.ws = new WebSocket(u); } catch (e) { return fallbackPoll(); }\n"
  "  state.ws.onopen = function () { $(\"live\").classList.add(\"live\"); state.pollFails = 0; };\n"
  "  state.ws.onmessage = function (e) {\n"
  "    try { lastSnap = JSON.parse(e.data); render(lastSnap); } catch (err) { }\n  };\n"
  "  state.ws.onclose = function () { $(\"live\").classList.remove(\"live\""
  "); setTimeout(reconnect, 1000); };\n"
  "  state.ws.onerror = function () { try { state.ws.close(); } catch (e) { } };\n}\n"
  "var lastSnap = null, tries = 0;\nfunction reconnect() {\n  if (tries < 3) {\n    tries++;\n"
  "    connect();\n  } else if (!state.pollTimer) {\n    fallbackPoll();\n  }\n}\n"
  "function fallbackPoll() {\n  clearInterval(state.pollTimer);\n  $(\"live\").classList.add(\""
  "poll\");\n  state.pollTimer = setInterval(function () {\n    fetch(\"/api/status\""
  ").then(function (r) { return r.json(); })\n"
  "      .then(function (d) { lastSnap = d; render(d); })\n      .catch(function () { });\n"
  "  }, 2000);\n  fetch(\"/api/status\""
  ").then(function (r) { return r.json(); }).then(function (d) { lastSnap = d; render(d); });\n}\n"
  "document.querySelectorAll(\".chip\").forEach(function (b) {\n  b.addEventListener(\"click\""
  ", function () {\n    var m = b.dataset.mode;\n    fetch(\"/api/mode?mode=\" + m, { method: \""
  "POST\" })\n      .then(function (r) { return r.json(); })\n      .then(function (j) { toast(\""
  "mode \342\206\222 \" + (j.mode || m)); })\n      .catch(function () { toast(\""
  "mode change failed\"); });\n  });\n});\n$(\"sort-w\").addEventListener(\"change\""
  ", function (e) {\n  localStorage.setItem(\"sort-w\""
  ", e.target.value); if (lastSnap) renderWifi(lastSnap); });\n$(\"sort-b\").addEventListener(\""
  "change\", function (e) {\n  localStorage.setItem(\"sort-b\""
  ", e.target.value); if (lastSnap) renderBle(lastSnap); });\n$(\"hide-w\").addEventListener(\""
  "change\", function () { if (lastSnap) renderWifi(lastSnap); });\n\nconnect();\n</script>\n"
  "</body>\n</html>";

static const size_t INDEX_HTML_LEN = sizeof(INDEX_HTML) - 1;
